Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -53,22 +53,22 @@ jobs:
             git push origin sa_test
           fi
 
-      # - name: Create temporary branch
-      #   run: |
-      #     git merge origin/source1 --no-commit --no-ff || echo "Merge failed"
+      - name: Create temporary branch
+        run: |
+          git merge origin/source1 --no-commit --no-ff || echo "Merge failed"
 
-      # - name: Check for merge conflicts
-      #   id: check_conflicts
-      #   run: |
-      #     if git ls-files -u | grep -q .; then
-      #       echo "Merge conflicts detected."
-      #       echo "conflicts=true" >> $GITHUB_ENV
-      #       git merge --abort  # Abort the merge
-      #     else
-      #       echo "No conflicts detected."
-      #       echo "conflicts=false" >> $GITHUB_ENV
-      #       # git commit -m "Merged source1 into sa_test"
-      #     fi
+      - name: Check for merge conflicts
+        id: check_conflicts
+        run: |
+          if git ls-files -u | grep -q .; then
+            echo "Merge conflicts detected."
+            echo "conflicts=true" >> $GITHUB_ENV
+            git merge --abort  # Abort the merge
+          else
+            echo "No conflicts detected."
+            echo "conflicts=false" >> $GITHUB_ENV
+            # git commit -m "Merged source1 into sa_test"
+          fi
 
       # - name: Sync to target1 (if no conflicts)
       #   if: env.conflicts == 'false'
