Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -57,35 +57,39 @@ jobs:
         id: merge_operation
         run: |
           git checkout sa_test
-          output=$(git merge origin/source1 2>&1) || {
-            echo "Merge failed. Output: $output"
-            if echo "$output" | grep -q "CONFLICT"; then
-               echo "Merge conflicts detected. Please resolve them."
-               git merge --abort
-            fi
-            exit 1
-          }
-          echo "Merge successful!"
-          git push origin sa_test               
+          output=$(git merge origin/source1 2>&1)
+          exit_code=$?  # Capture the exit code right after the command
+          echo "Exit Code is : $exit_code"
+
+          # output=$(git merge origin/source1 2>&1) || {
+          #   echo "Merge failed. Output: $output"
+          #   if echo "$output" | grep -q "CONFLICT"; then
+          #      echo "Merge conflicts detected. Please resolve them."
+          #      git merge --abort
+          #   fi
+          #   exit 1
+          # }
+          # echo "Merge successful!"
+          # git push origin sa_test               
           
      
-      - name: Sync to target1 (if no conflicts)        
-        run: |
-          git checkout target1
-          output=$(git merge origin/source1 2>&1) || {
-            echo "Merge failed. Output: $output"
-            if echo "$output" | grep -q "CONFLICT"; then
-               echo "Merge conflicts detected. Please resolve them."
-               git merge --abort
-            fi
-            exit 1
-          }
-          echo "Merge successful!"
-          git push origin target1               
+      # - name: Sync to target1 (if no conflicts)        
+      #   run: |
+      #     git checkout target1
+      #     output=$(git merge origin/source1 2>&1) || {
+      #       echo "Merge failed. Output: $output"
+      #       if echo "$output" | grep -q "CONFLICT"; then
+      #          echo "Merge conflicts detected. Please resolve them."
+      #          git merge --abort
+      #       fi
+      #       exit 1
+      #     }
+      #     echo "Merge successful!"
+      #     git push origin target1               
           
 
-      - name: Clean up temporary branch        
-        run: |
-          git branch -d sa_test  # Delete the local sa_test branch
-          git push origin --delete sa_test  # Delete the remote sa_test branch
-          echo "sa_test branch has been deleted."
+      # - name: Clean up temporary branch        
+      #   run: |
+      #     git branch -d sa_test  # Delete the local sa_test branch
+      #     git push origin --delete sa_test  # Delete the remote sa_test branch
+      #     echo "sa_test branch has been deleted."
