Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -53,16 +53,16 @@ jobs:
       #       git push origin sa_test
       #     fi
 
-      - name: Merge Operation
-        id: merge_operation
-        run: |
-          git checkout sa_test
-          git merge origin/source1
-          # if [ $? -ne 0 ]; then
-          #  echo "Merge failed: $output"
-          #  echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
-          #  exit 1  # Exit with an error code to stop the workflow
-          # fi
+      # - name: Merge Operation
+      #   id: merge_operation
+      #   run: |
+      #     git checkout sa_test
+      #     git merge origin/source1
+      #     # if [ $? -ne 0 ]; then
+      #     #  echo "Merge failed: $output"
+      #     #  echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
+      #     #  exit 1  # Exit with an error code to stop the workflow
+      #     # fi
          
           
       # - name: Display merge output
