Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -59,12 +59,12 @@ jobs:
           git checkout sa_test
           output=$(git merge origin/source1 --no-commit --no-ff 2>&1) || echo "Merge failed: $output" 
           
-          if [ $? -ne 0 ]; then
-            echo "Merge failed" >> $GITHUB_ENV
-            echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
-          else
-            echo "Merge successful"
-            echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
+          # if [ $? -ne 0 ]; then
+          #   echo "Merge failed" >> $GITHUB_ENV
+          #   echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
+          # else
+          #   echo "Merge successful"
+          #   echo "merge_output=${output//$'\n'/\\n}" >> $GITHUB_ENV
             
       #       # Check for changes before committing
       #       if [ -n "$(git status --porcelain)" ]; then
