Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -60,20 +60,20 @@ jobs:
           output=$(git merge origin/source1 2>&1)
 
           # Check if the merge was successful
-          if [[ $? -ne 0 ]]; then
-            echo "Merge failed. Output:"
-            echo "$output"
-            if echo "$output" | grep -q "CONFLICT"; then
-               echo "Merge conflicts detected. Please resolve them."
-               # Optional: Abort the merge
-               git merge --abort
-               exit 1
-            fi
-          else
-             echo "Merge successful!"
-             # Push the changes if needed
-             git push origin sa_test
-          fi
+          # if [[ $? -ne 0 ]]; then
+          #   echo "Merge failed. Output:"
+          #   echo "$output"
+          #   if echo "$output" | grep -q "CONFLICT"; then
+          #      echo "Merge conflicts detected. Please resolve them."
+          #      # Optional: Abort the merge
+          #      git merge --abort
+          #      exit 1
+          #   fi
+          # else
+          #    echo "Merge successful!"
+          #    # Push the changes if needed
+          #    git push origin sa_test
+          # fi
         
           # git merge origin/source1
           # if [ $? -ne 0 ]; then
