Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -54,7 +54,7 @@ jobs:
           fi
 
       - name: Merge Operation
-        id: merge_operation
+        id: merge_operation_sa_test
         run: |
           git checkout sa_test
           # Merge operation using a subshell
@@ -73,39 +73,30 @@ jobs:
            exit 1  # Exit with an error code
           fi
 
-          # output=$(git merge origin/source1 2>&1)
-          # exit_code=$?  # Capture the exit code right after the command
-          # echo "Exit Code is : $exit_code"
-
-          # output=$(git merge origin/source1 2>&1) || {
-          #   echo "Merge failed. Output: $output"
-          #   if echo "$output" | grep -q "CONFLICT"; then
-          #      echo "Merge conflicts detected. Please resolve them."
-          #      git merge --abort
-          #   fi
-          #   exit 1
-          # }
-          # echo "Merge successful!"
-          # git push origin sa_test               
-          
-     
-      # - name: Sync to target1 (if no conflicts)        
-      #   run: |
-      #     git checkout target1
-      #     output=$(git merge origin/source1 2>&1) || {
-      #       echo "Merge failed. Output: $output"
-      #       if echo "$output" | grep -q "CONFLICT"; then
-      #          echo "Merge conflicts detected. Please resolve them."
-      #          git merge --abort
-      #       fi
-      #       exit 1
-      #     }
-      #     echo "Merge successful!"
-      #     git push origin target1               
+              
+      - name: Merge Operation on target1  
+        id: merge_operation_target1
+        run: |
+          git checkout target1
+          # Merge operation using a subshell
+          if output=$(git merge origin/source1 2>&1); then
+            echo "Merge successful!"
+            # Optionally push changes if needed
+            git push origin target1
+          else
+            echo "Error: $output"  # Output from the failed command
+            if echo "$output" | grep -q "CONFLICT"; then
+               echo "Merge conflicts detected. Please resolve them."
+               git merge --abort  # Abort the merge if there are conflicts
+           else
+              echo "An error occurred during the merge (not a conflict)."
+           fi
+           exit 1  # Exit with an error code
+          fi              
           
 
-      # - name: Clean up temporary branch        
-      #   run: |
-      #     git branch -d sa_test  # Delete the local sa_test branch
-      #     git push origin --delete sa_test  # Delete the remote sa_test branch
-      #     echo "sa_test branch has been deleted."
+      - name: Clean up temporary branch        
+        run: |
+          git branch -d sa_test  # Delete the local sa_test branch
+          git push origin --delete sa_test  # Delete the remote sa_test branch
+          echo "sa_test branch has been deleted."
