Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -41,7 +41,7 @@ jobs:
 
       - name: Create or reset sa_test branch
         run: |
-          if [ ${{ env.branch_exists == 'true' }} ]; then
+          if [ "${{ env.branch_exists }}" == "true" ]; then
             git checkout sa_test
             # git reset --hard origin/source1  # Reset temp1 to the latest from source1
           else
@@ -52,31 +52,31 @@ jobs:
             git push origin sa_test
           fi
 
-      - name: Create temporary branch
-        run: |
-          git merge origin/source1 --no-commit --no-ff || echo "Merge failed"
+      # - name: Create temporary branch
+      #   run: |
+      #     git merge origin/source1 --no-commit --no-ff || echo "Merge failed"
 
-      - name: Check for merge conflicts
-        id: check_conflicts
-        run: |
-          if git ls-files -u | grep -q .; then
-            echo "Merge conflicts detected."
-            echo "conflicts=true" >> $GITHUB_ENV
-            git merge --abort  # Abort the merge
-          else
-            echo "No conflicts detected."
-            echo "conflicts=false" >> $GITHUB_ENV
-            # git commit -m "Merged source1 into sa_test"
-          fi
+      # - name: Check for merge conflicts
+      #   id: check_conflicts
+      #   run: |
+      #     if git ls-files -u | grep -q .; then
+      #       echo "Merge conflicts detected."
+      #       echo "conflicts=true" >> $GITHUB_ENV
+      #       git merge --abort  # Abort the merge
+      #     else
+      #       echo "No conflicts detected."
+      #       echo "conflicts=false" >> $GITHUB_ENV
+      #       # git commit -m "Merged source1 into sa_test"
+      #     fi
 
-      - name: Sync to target1 (if no conflicts)
-        if: env.conflicts == 'false'
-        run: |
-          git checkout target1
-          git merge sa_test
-          git push origin target1
+      # - name: Sync to target1 (if no conflicts)
+      #   if: env.conflicts == 'false'
+      #   run: |
+      #     git checkout target1
+      #     git merge sa_test
+      #     git push origin target1
 
-      - name: Clean up temporary branch
-        if: env.conflicts == 'false'
-        run: |
-          git branch -D sa_test
+      # - name: Clean up temporary branch
+      #   if: env.conflicts == 'false'
+      #   run: |
+      #     git branch -D sa_test
